### ISSUE TITLE
module' object has no attribute 'parse' issue

### ISSUE THREAD

**Issue by wmariuss** [msleal/amspy#8]
There is an issue when I call for a token and list all media files.
The issue is: `module' object has no attribute 'parse' issue`

So, to fix this I updated this line:
https://github.com/msleal/amspy/blob/master/amspy/amsrest.py#L17
with `accountkey_encoded = urllib.pathname2url(accountkey)`

**Comment by msleal** [comment]
Hi wmariuss,
   Thanks for the feedback and patch, I will take a look into this and answer asap.
-- Leal
